<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted} from 'vue'
import {useRouter} from 'vue-router'
import {Plus,ArrowUpRight,Search,LayoutGrid,List,Upload,BookOpen,Sparkles,Download,ArrowRight,MoreHorizontal,Trash2,FileArchive,RefreshCw} from 'lucide-vue-next'
import {useStore} from '../store'
import {api,post,statusLabels,date,type Book} from '../api'
import BookCover from '../components/BookCover.vue'
const store=useStore(),router=useRouter(),query=ref(''),filter=ref('all'),layout=ref('grid'),busy=ref(false),deleteTarget=ref<Book|null>(null),importInput=ref<HTMLInputElement|null>(null),menu=ref('')
const filtered=computed(()=>store.books.filter(b=>(filter.value==='all'||b.status===filter.value)&&(b.title+b.author).toLowerCase().includes(query.value.toLowerCase())))
const ready=computed(()=>store.books.filter(b=>b.status==='ready').length)
let polling:ReturnType<typeof setInterval>
onMounted(()=>{store.loadBooks();polling=setInterval(()=>{if(store.books.some(b=>b.status==='generating'))store.loadBooks()},4000)})
onUnmounted(()=>clearInterval(polling))
async function addDemo(){busy.value=true;try{await post('/demo');await store.loadBooks();store.notify('已添加原创示例，可查看 Skill 与原文；问书需配置 AI')}catch(e){store.notify((e as Error).message)}finally{busy.value=false}}
async function importFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;busy.value=true;try{const data=new FormData();data.append('file',f);const b=await api<Book>('/skills/import',{method:'POST',body:data});await store.loadBooks();store.notify('Skill 导入成功');router.push('/books/'+b.id+'/skill')}catch(e){store.notify((e as Error).message)}finally{busy.value=false;(e.target as HTMLInputElement).value=''}}
async function remove(){if(!deleteTarget.value)return;try{await api('/books/'+deleteTarget.value.id,{method:'DELETE'});deleteTarget.value=null;await store.loadBooks();store.notify('书籍及相关数据已删除')}catch(e){store.notify((e as Error).message)}}
</script>
<template><section class="library-page page">
 <div class="page-heading"><div><div class="eyebrow"><span class="tiny-line"></span>YOUR KNOWLEDGE, REIMAGINED</div><h1>我的 AI 书架<span class="heading-dot">.</span></h1><p>不止读过一本书，让它成为你随时可调用的知识。</p></div><RouterLink to="/books/new" class="button primary"><Plus :size="18"/>添加一本书</RouterLink></div>
 <div class="library-banner"><div class="banner-copy"><div class="banner-tag"><Sparkles :size="14"/>从阅读，到理解</div><h2>一本好书，<br/>可以有无数次新的对话。</h2><p>把电子书转化成专属 AI Skill。探索思想，追溯原文，<br class="desktop"/>让书里的智慧走进你的日常。</p><RouterLink to="/books/new" class="banner-link">开始你的下一次阅读<ArrowUpRight :size="17"/></RouterLink></div><div class="banner-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-word">READ.<br/>THINK.<br/><em>CONNECT.</em></div><div class="art-book"><div class="art-book-line"></div><span>BOOK<br/><i>to</i><br/>SKILL</span><BookOpen :size="30" :stroke-width="1"/></div><span class="art-label">让知识有回响</span><span class="art-star">✳</span></div></div>
 <div class="shelf-top"><div class="shelf-tabs"><button :class="{selected:filter==='all'}" @click="filter='all'">全部书籍<span>{{store.books.length}}</span></button><button :class="{selected:filter==='ready'}" @click="filter='ready'">可问书<span>{{ready}}</span></button><button :class="{selected:filter==='generating'}" @click="filter='generating'">生成中<span>{{store.books.filter(b=>b.status==='generating').length}}</span></button></div><div class="shelf-controls"><label class="search-box"><Search :size="16"/><input v-model="query" placeholder="搜索书名、作者…" aria-label="搜索书名、作者"/><kbd>⌕</kbd></label><div class="layout-switch"><button :class="{selected:layout==='grid'}" @click="layout='grid'" aria-label="网格视图"><LayoutGrid :size="17"/></button><button :class="{selected:layout==='list'}" @click="layout='list'" aria-label="列表视图"><List :size="19"/></button></div></div></div>
 <div class="shelf-summary"><span>{{filtered.length}} 本书 · {{ready}} 个知识 Skill</span><button class="text-link" :disabled="busy" @click="importInput?.click()"><FileArchive :size="14"/>导入 Skill<ArrowUpRight :size="13"/></button><input ref="importInput" class="hidden" type="file" accept=".zip" @change="importFile"/></div>
 <div v-if="store.error" class="error-box">{{store.error}}<button class="text-link" @click="store.loadBooks()">重新连接</button></div>
 <div v-else-if="store.loading&&!store.books.length" class="loading-block"><RefreshCw class="spin" :size="22"/>正在打开你的书架…</div>
 <div v-else-if="!store.books.length" class="empty-shelf"><div class="empty-book-icon"><BookOpen :size="36" :stroke-width="1.2"/><span>+</span></div><h3>每一座知识书架，都从第一本书开始</h3><p>上传 EPUB、PDF、TXT 或 Markdown<br/>把你正在读的书，变成可以与你对话的 Skill。</p><RouterLink to="/books/new" class="button primary"><Upload :size="16"/>上传第一本书</RouterLink><button class="empty-demo" :disabled="busy" @click="addDemo">{{busy?'正在添加…':'或先用原创示例探索一下'}}<ArrowRight :size="14"/></button></div>
 <div v-else-if="!filtered.length" class="empty-shelf compact"><Search :size="30"/><h3>没有找到对应的书籍</h3><p>试试其他关键词或切换书籍状态。</p><button class="button" @click="query='';filter='all'">查看全部书籍</button></div>
 <div v-else class="books-grid" :class="{'books-list':layout==='list'}"><article v-for="b in filtered" :key="b.id" class="book-card"><RouterLink :to="'/books/'+b.id" class="book-cover-link"><BookCover :book="b"/><span class="cover-open">打开这本书<ArrowUpRight :size="16"/></span></RouterLink><div class="book-card-info"><div class="book-title-row"><RouterLink :to="'/books/'+b.id"><h3>{{b.title}}</h3></RouterLink><div class="menu-wrap"><button class="icon-button" @click="menu=menu===b.id?'':b.id" aria-label="书籍操作"><MoreHorizontal :size="18"/></button><div v-if="menu===b.id" class="dropdown"><RouterLink :to="'/books/'+b.id+'/skill'" @click="menu=''">查看 Skill</RouterLink><a v-if="b.metadata" :href="'/api/books/'+b.id+'/export'" @click="menu=''">导出 Skill</a><button class="danger" @click="deleteTarget=b;menu=''">删除书籍</button></div></div></div><p class="book-author">{{b.author}}</p><div class="book-card-footer"><span class="status-badge" :class="b.status"><span></span>{{statusLabels[b.status]||b.status}}</span><span class="book-date">{{date(b.createdAt)}}</span></div><div v-if="b.status==='generating'" class="mini-progress"><i :style="{width:b.progress+'%'}"/></div></div></article><RouterLink to="/books/new" class="add-book-card"><span><Plus :size="26" :stroke-width="1.2"/></span><strong>留一个位置<br/>给下一本好书</strong><small>EPUB / PDF / TXT / MD</small></RouterLink></div>
 <footer class="library-footer"><span><BookOpen :size="15"/>好书不止读一遍，知识可以一直生长。</span><span>SKILL FIRST. UNDERSTANDING ALWAYS.</span></footer>
 </section><div v-if="deleteTarget" class="modal-backdrop" @click.self="deleteTarget=null"><div class="modal"><Trash2 :size="26" class="danger"/><h2>删除《{{deleteTarget.title}}》？</h2><p>将同时删除原始电子书、Book Skill、原文索引、笔记和所有问书记录。此操作无法恢复。</p><div class="modal-actions"><button class="button" @click="deleteTarget=null">取消</button><button class="button danger-button" @click="remove">确认删除</button></div></div></div>
</template>
