<script setup lang="ts">
import {reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {Eye,EyeOff,ShieldCheck,Check,LoaderCircle,PlugZap,Save,ArrowLeft,KeyRound,SlidersHorizontal,ExternalLink} from 'lucide-vue-next'
import {post} from '../api'
import {useStore} from '../store'
const store=useStore(),route=useRoute(),router=useRouter(),form=reactive({...store.config}),show=ref(false),testing=ref(false),saving=ref(false),result=ref(''),error=ref('')
watch(()=>store.config,v=>Object.assign(form,v),{deep:true})
watch(form,()=>{result.value='';error.value=''})
function validate(){if(!/^https?:\/\/[^\s]+$/.test(form.baseURL))throw new Error('请输入有效的 HTTP(S) API URL');if(!form.model.trim())throw new Error('请输入模型名称');if(form.temperature<0||form.temperature>2)throw new Error('Temperature 应为 0–2');if(form.maxTokens<256||form.maxTokens>65536)throw new Error('Max Tokens 应为 256–65536')}
async function test(){testing.value=true;error.value='';result.value='';try{validate();await post('/settings/test',form);result.value='连接成功 · AI 服务可用'}catch(e){error.value=(e as Error).message}finally{testing.value=false}}
async function save(){saving.value=true;error.value='';try{validate();await store.saveConfig({...form,baseURL:form.baseURL.trim().replace(/\/$/,''),model:form.model.trim()});store.notify('AI 设置已保存到此浏览器');if(typeof route.query.return==='string'&&route.query.return.startsWith('/books/'))router.push(route.query.return)}catch(e){error.value=(e as Error).message}finally{saving.value=false}}
</script>
<template><section class="page settings-page"><RouterLink to="/" class="back-link"><ArrowLeft :size="16"/>返回书架</RouterLink><div class="page-heading"><div><div class="eyebrow">YOUR MODEL, YOUR CHOICE.</div><h1>让 AI 加入你的阅读</h1><p>连接你自己的模型，使用你习惯的 AI 服务。</p></div></div><div class="settings-layout"><form class="settings-card" @submit.prevent="save"><div class="card-heading"><PlugZap :size="20"/><h2>AI 模型配置</h2><span>OpenAI Compatible</span></div><label class="field-label">API URL<input v-model="form.baseURL" type="url" placeholder="https://api.openai.com/v1" required/><small>填写接口基础地址，例如以 /v1 结尾；无需填写 /chat/completions。</small></label><label class="field-label">API Key<div class="password-input"><input v-model="form.apiKey" :type="show?'text':'password'" autocomplete="off" placeholder="sk-…（本地模型可留空）"/><button type="button" class="icon-button" @click="show=!show" :aria-label="show?'隐藏 API Key':'显示 API Key'"><EyeOff v-if="show" :size="18"/><Eye v-else :size="18"/></button></div></label><label class="field-label">Model<input v-model="form.model" placeholder="输入服务商的模型名称" required/><small>支持 OpenAI、DeepSeek、OpenRouter、Ollama 等兼容服务。</small></label><div class="field-row"><label class="field-label">Temperature<input v-model.number="form.temperature" type="number" step="0.1" min="0" max="2" required/><small>较低的值让回答更稳定</small></label><label class="field-label">Max Tokens<input v-model.number="form.maxTokens" type="number" step="256" min="256" max="65536" required/><small>单次回答的最大输出长度</small></label></div><details class="advanced-settings"><summary><SlidersHorizontal :size="15"/>可选 · 混合检索</summary><label class="field-label">Embedding Model<input v-model="form.embeddingModel" placeholder="留空使用 BM25 全文检索"/><small>启用后按 0.4 关键词 + 0.6 语义相似度检索。调用同一服务的 /embeddings，可能产生额外费用；候选集最多 80 条。</small></label></details><div v-if="result" class="success-box" role="status"><Check :size="17"/>{{result}}</div><div v-if="error" class="error-box" role="alert">{{error}}</div><div class="settings-actions"><button type="button" class="button" :disabled="testing" @click="test"><LoaderCircle v-if="testing" class="spin" :size="16"/><PlugZap v-else :size="16"/>{{testing?'测试中…':'测试连接'}}</button><button class="button primary" :disabled="saving"><Save :size="16"/>保存设置</button></div></form><aside class="settings-help"><div class="help-icon"><ShieldCheck :size="28" :stroke-width="1.3"/></div><h3>你的密钥，只属于你</h3><p>API Key 仅用于调用你配置的 AI 服务。</p><ul><li>保存于浏览器 IndexedDB</li><li>不写入服务器数据库或日志</li><li>请求期间临时传给本地 Worker</li><li>任务结束后释放密钥</li></ul><div class="help-divider"></div><h4>本地模型也可以</h4><p>例如 Ollama：<code>http://localhost:11434/v1</code>，Key 可以留空。</p><p>浏览器清除网站数据后，需要重新填写配置。</p></aside></div></section></template>
