<script setup lang="ts">
import {ref,watch} from 'vue'
import {useRouter} from 'vue-router'
import {Upload,FileText,ArrowRight,Check,ShieldCheck,BookOpen,LoaderCircle,ArrowLeft,Settings,Sparkles} from 'lucide-vue-next'
import {api,post,type Book,type Estimate} from '../api'
import {useStore} from '../store'
const router=useRouter(),store=useStore(),input=ref<HTMLInputElement|null>(null),busy=ref(false),drag=ref(false),error=ref(''),book=ref<Book|null>(null),estimate=ref<Estimate|null>(null),filename=ref(''),purpose=ref('all')
async function process(f?:File){if(!f||busy.value)return;error.value='';if(f.size>50*1024*1024){error.value='文件超过 50 MB 限制';return}busy.value=true;filename.value=f.name;try{const body=new FormData();body.append('file',f);const result=await api<{book:Book;estimate:Estimate;duplicate:boolean}>('/books',{method:'POST',body});book.value=result.book;estimate.value=result.estimate;if(result.duplicate)store.notify('这本书已在书架中，已打开现有记录');await store.loadBooks()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function drop(e:DragEvent){drag.value=false;process(e.dataTransfer?.files[0])}
async function start(){if(!book.value)return;if(!store.config.model){router.push('/settings?return='+encodeURIComponent('/books/'+book.value.id));return}busy.value=true;try{await post('/books/'+book.value.id+'/generate',{config:store.config,purpose:purpose.value});router.push('/books/'+book.value.id)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
watch(purpose,async()=>{if(book.value){try{estimate.value=await api('/books/'+book.value.id+'/estimate?purpose='+purpose.value)}catch(e){error.value=(e as Error).message}}})
</script>
<template><section class="page centered-page"><RouterLink to="/" class="back-link"><ArrowLeft :size="16"/>返回书架</RouterLink><div class="center-heading"><div class="eyebrow">A BOOK. A NEW POSSIBILITY.</div><h1>把一本书，变成知识 Skill</h1><p>整本理解，结构化提炼，随时开启一场有依据的对话。</p></div>
 <div v-if="!book" class="upload-zone" :class="{drag,busy}" @dragover.prevent="drag=true" @dragleave.prevent="drag=false" @drop.prevent="drop"><div class="upload-icon"><LoaderCircle v-if="busy" :size="38" class="spin"/><Upload v-else :size="38" :stroke-width="1.2"/></div><h2>{{busy?'正在读取电子书…':'把你的下一本好书放在这里'}}</h2><p>{{busy?filename:'拖入文件，或者从电脑中选择'}}</p><button class="button primary" :disabled="busy" @click="input?.click()"><Upload :size="16"/>选择电子书<ArrowRight :size="16"/></button><input ref="input" class="hidden" type="file" accept=".epub,.pdf,.txt,.md,.markdown" @change="process(($event.target as HTMLInputElement).files?.[0])"/><div class="file-formats"><span>EPUB</span><span>PDF</span><span>TXT</span><span>Markdown</span><small>最大 50 MB</small></div></div>
 <div v-else class="upload-result"><div class="success-circle"><Check :size="24"/></div><div class="eyebrow">BOOK PARSED</div><h2>{{book.title}}</h2><p>{{book.author}} · {{book.chapterCount}} 个章节</p><label class="purpose-choice">这份 Skill 应该帮助你做什么？<select v-model="purpose" aria-label="Skill 用途"><option value="all">综合理解与应用（深入学习）</option><option value="apply">应用作者的框架（深入学习）</option><option value="think">用作者的心智模型思考（深入学习）</option><option value="reference">快速查阅章节与概念（精简参考）</option></select></label><div class="estimate-grid"><div><strong>{{estimate?.tokens.toLocaleString()}}</strong><span>原书 Tokens 估算</span></div><div><strong>{{estimate?.sections}}</strong><span>分析片段</span></div><div><strong>≈ {{estimate?.requests}}</strong><span>预计 AI 请求</span></div></div><p class="hint">参考 book-to-skill，先提取框架，再生成按需章节知识与决策工具。预算包含逐章知识文件及综合调用，实际用量取决于模型输出。{{estimate?.checkpoints?'已有 '+estimate.checkpoints+' 个检查点可复用。':''}}</p><p class="hint" v-if="estimate?.outputTokens">估算输出预算上限约 {{estimate.outputTokens.toLocaleString()}} Tokens；精简章节不会为达到预算而填充。</p><div class="notice" v-if="!store.config.model"><Settings :size="18"/><span>请先配置你的 AI 模型，才能开始知识蒸馏。</span></div><button v-if="book.status!=='ready'&&book.status!=='generating'" class="button primary wide" :disabled="busy" @click="start"><Sparkles :size="17"/>{{busy?'正在启动…':store.config.model?'开始转换为 Skill':'配置 AI 并开始转换'}}<ArrowRight :size="17"/></button><RouterLink v-else :to="'/books/'+book.id" class="button primary wide">{{book.status==='ready'?'开始问书':'查看生成进度'}}<ArrowRight :size="17"/></RouterLink><button class="text-link center" @click="book=null;error=''">继续添加另一本</button></div>
 <div v-if="error" class="error-box" role="alert">{{error}}</div><div class="upload-privacy"><ShieldCheck :size="17"/>文件存储在本地，不会公开分享。转换时正文将发送到你配置的 AI 服务。</div><div class="how-it-works"><div><span>01</span><BookOpen :size="20"/><h3>解析整本书</h3><p>识别目录与章节<br/>保留完整原文</p></div><div><span>02</span><Sparkles :size="20"/><h3>提炼知识 Skill</h3><p>整理概念、观点和方法<br/>建立跨章节联系</p></div><div><span>03</span><FileText :size="20"/><h3>带着依据问书</h3><p>按需调用知识<br/>每个出处都可以追溯</p></div></div></section></template>
